import type { Metadata } from "next";
import "./globals.css";
import CommonFunctions from "@/components/CommonFunctions/CommonFunctions";

export const metadata: Metadata = {
  title: "Informal | Yash",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <div className="p-8 md:p-20 flex flex-col items-center">
          <div className="w-full max-w-[40em]">{children}</div>
        </div>
        <CommonFunctions />
      </body>
    </html>
  );
}
